spring:
  application:
    name: TaxRefundApp
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:file:./build/h2db/db/recruit-3o3-test;DB_CLOSE_DELAY=-1
    username: young-jun
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      path: /h2-console
      enabled: true

server:
  port: 8080